name: Docker build and push - client

on:
  pull_request:

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login Docker
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

      - name: Docker build
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          cd CinemaPlusFront/cinema_react && docker build -t $DOCKERHUB_REPO:client.v2.6 .

      - name: Docker push
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          docker push $DOCKERHUB_REPO:client.v2.6
